### ISSUE TITLE
bankswitching to the fixed bank

### ISSUE THREAD

**Issue by zlago** [zenzoa/piropa#1]
alright so frog graphics data lives in the fixed bank, but the code still performs a bankswitch, which is not exactly supposted to happen??
fix: unknown?? move frog graphics to `romx` if possible?

**Comment by zenzoa** [comment]
Theoretically the frog graphics data should live in... not a fixed bank. GBDK's autobanking is supposed to assign things to banks automatically. Maybe it's assigning them to bank zero since there's room in there? Or even more possibly I set up autobanking incorrectly!
